### ISSUE TITLE
Missing toggle in scene settings.

### ISSUE THREAD

**Issue by AurelTristen** [SDoehren/day-night-cycle#12]
**Describe the bug**
Unless I'm somehow missing it, I don't see any option to toggle Day Night Cycle on or off per-scene. I've disabled all modules but this one (and its dependencies) and still can't find it. Perhaps this is a V12 bug since they changed scenes so much?
**To Reproduce**
1. Create a new scene or edit an existing one (I tried both)
2. No toggle option found.

**Expected behavior**
I expected there might be a checkbox in the lighting or ambience tabs, but I checked every tab.

**Foundry (please complete the following information):**
 - Foundry Version v12.330
 - System D&D 5e 3.3.1
 - Module Version 0008
**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser TheRipper's FVTT Client (Electron)

And if you'll allow an unrelated question, I was curious if you might enable the module to change the scene's Environment Lighting (added in V12) over time. For example, warm light for sunsets/rises. Perhaps a blue tint to night/moon light. I actually found this module while trying to find a script/macro that changes environment lighting, so I could do sun rises/sunsets manually. Even without this request, I'd love to get the module working!
Thank you.

**Comment by SDoehren** [comment]
I will investigate.  

On the side question.  it is something that would be interesting to do.

**Comment by humburg** [comment]
I can confirm that I see the same issue with module version 0009 on Foundry 12.331.

**Comment by StrangeWill** [comment]
An error gets thrown upon opening the scene's configuration:

```
Error: Error thrown in hooked function '' for hook 'renderSceneConfig'. Cannot read properties of undefined (reading 'flags')
[Detected 1 package: day-night-cycle(0009)]
    at Hooks.onError (foundry.js:654:24)
    at 🎁Hooks.onError#0 (libWrapper-wrapper.js:188:54)
    at #call (foundry.js:636:36)
    at Hooks.callAll (foundry.js:589:17)
    at SceneConfigPF2e._callHooks (foundry.js:5918:13)
    at SceneConfigPF2e._render (foundry.js:5879:10)
    at async SceneConfigPF2e._render (foundry.js:6572:5)
    at async SceneConfigPF2e._render (foundry.js:7158:5)Caused by: TypeError: Cannot read properties of undefined (reading 'flags')
[Detected 1 package: day-night-cycle(0009)]
    at Object.fn (day-night-cycle.js:46:38)
    at #call (foundry.js:632:20)
    at Hooks.callAll (foundry.js:589:17)
    at SceneConfigPF2e._callHooks (foundry.js:5918:13)
    at SceneConfigPF2e._render (foundry.js:5879:10)
    at async SceneConfigPF2e._render (foundry.js:6572:5)
    at async SceneConfigPF2e._render (foundry.js:7158:5)
```

Foundry dev is pretty new to me but I may submit a PR to fix this before our next session (4 weeks)

**Comment by StrangeWill** [comment]
Fixed in PR #14 from what I can tell, I've only done some preliminary testing but I think this is what we expect.
